export const CREATE_ITEM_REQUEST = "CREATE_ITEM_REQUEST";
export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FOLLOW_CAMPAIGN_REQUEST =
  "GET_ITEMS_FOLLOW_CAMPAIGN_REQUEST";
export const DELETE_ITEMS_REQUEST = "DELETE_ITEMS_REQUEST";
export const UPDATA_ITEM_EDIT_TO_REDUX = "UPDATA_ITEM_EDIT_TO_REDUX";

export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST";
