export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const CHANGE_STATUS_REQUEST ="CHANGE_STATUS_REQUEST";
